# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "206b7fba84bcfd94b6a64ff39dce171d"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "checkout-extension-app"
handle = "checkout-extension-app-101"

[build]
include_config_on_deploy = true
dev_store_url = "printfreshpractice.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
